### ISSUE TITLE
按说明安装运行install.bat，出现如图问题，何解？

### ISSUE THREAD

**Issue by anymee** [Cozak/ThunderAPIHelper_WebExt#1]
![6](https://user-images.githubusercontent.com/31944592/32685028-edd864ce-c6c4-11e7-9ac9-efff6725d30e.png)

**Comment by Cozak** [comment]
Git自动转换了文本的回车换行符，把Windows(CRLF)换成Unix(LF)了，所以bat无法正常解析命令
下一个notepad++参照[这里](http://www.cuixinjiang.cn/wzzhizuo/784.html)的方法转换install.bat和uninstall.bat的回车缩进为windows风格即可

**Comment by anymee** [comment]
谢谢！我试试

**Comment by anymee** [comment]
"ESR版仍允许使用旧插件和拓展（需要在about:config设置一下），能提供调用迅雷所需的NPAPI接口"

请问具体怎么设置？没有找到

**Comment by Cozak** [comment]
搜“firefox 允许未验证插件”，设置后查看“附加组件--插件”，能找到xunlei插件

**Comment by anymee** [comment]
请问：是xpinstall.signatures.required，改成false吗？
设置好了还是看不到迅雷插件。
调试ThunderAPIHelper出现错误，如下：
![5](https://user-images.githubusercontent.com/31944592/32882188-847753c2-caee-11e7-9fe4-6620226f6da3.png)

下载链接打开后点击下载没有反应，用的Firefox ESR,

**Comment by Cozak** [comment]
在“附加组件--插件”页是不是显示“少些东西？某些插件已不再被firefox支持”，点击“[详细了解](https://support.mozilla.org/zh-CN/kb/npapi-plugins?as=u&utm_source=inproduct)“有说明

1）注意只有ESR 32位版本支持旧插件，64位不行
2）plugin.load_flash_only = false （默认配置）

确保XunLei插件存在，点击“开始下载”才有反应
![--](https://user-images.githubusercontent.com/10653478/32950576-bfe95362-cbe1-11e7-8175-4e2bd7d8d5f4.PNG)

**Comment by anymee** [comment]
上图的两个xuelei插件没有，怎么安装？不是安装了ThunderAPIHelper_WebExt就有吗？到哪里下载安装？谢谢！

**Comment by Cozak** [comment]
ThunderAPIHelper_WebExt与那两个XunLei插件之间不存在依赖关系的，只要你的浏览器版本还支持NPAPI插件（那两个XunLei插件）就不需要安装ThunderAPIHelper_WebExt扩展

ThunderAPIHelper_webExt是为了应对日后浏览器不再支持NPAPI插件的情况才开发的

简而言之，如果要让“开始下载”有反应，那么有两种方法
1）浏览器支持XunLei插件（目前Firefox ESR 32位版本仍支持）
2）安装ThunderAPIHelper_WebExt扩展（Firefox正式版 50+、ESR版50+都支持）

PS：XunLei插件貌似已经下架，火狐扩展官网上找不到了（9月份的时候还有）
PS：如果只是为了下载方便用“复制链接”即可，ThunderAPIHelper_WebExt仅供试用或作为WebExtensions参考样例

**Comment by anymee** [comment]
明白了，谢谢！

我现在装的就是Firefox ESR 32位版本，请问在哪里能找到XunLei插件？因为想在线播放视频。Firefox应用程序项找不到ASX这一项，据说是需要下载一次ASX文件之后才可以设置，求解？

**Comment by anymee** [comment]
已经安装了ThunderAPIHelper_WebExt扩展，下载按钮仍然没有反应的

**Comment by Cozak** [comment]
XunLei插件已下架，而且刚折腾一阵，发现其实现在使用FireFox开发版（Developer Edition）更好（刚换到Firefox DE 58
![firefoxde57](https://user-images.githubusercontent.com/10653478/33054383-d8a6ef98-ceb3-11e7-8724-80b5628449b2.PNG)
）
不仅可以使用最新特性而且新版Firefox（57+）比前面的版本用起来流畅了不止一倍，另外安装未验证插件也简单了很多，可以看看我刚刚更新的README

关联ASX文件步骤：
浏览器下载一次ASX文件，在弹出的下载窗口处选择“打开”，默认的程序选择“potplayer”即可

**Comment by anymee** [comment]
我试试。

到哪里找ASX文件来下载，比如给个网址啥的？

**Comment by Cozak** [comment]
在115网盘里随便找个视频文件点击“播放”即可（对于新版Firefox就是下载一个ASX文件，然后选择本地默认程序打开）

**Comment by anymee** [comment]
![default](https://user-images.githubusercontent.com/31944592/33107136-c605a7c2-cf70-11e7-8e4c-1b49abfe8977.gif)

点击下载后出来这个，显示下载创建成功，到哪里找下载的文件？

**Comment by anymee** [comment]
另外，在115网盘里随便找个视频文件点击“播放”需要VIP的吧？没有VIP好像不好播放啊

**Comment by Cozak** [comment]
115脚步添加的“播放”，不是VIP的
![play](https://greasyfork.org/system/screenshots/screenshots/000/007/086/original/%E7%82%B9%E6%92%AD%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6.png?1493371252)

你是怎么下载的？点击“开始下载”弹出的那个迅雷弹窗么？检查一下“附加组件--插件”里面是不是有XunLei插件

**Comment by anymee** [comment]
现在突然可以在线播放了，但没有你上图的那个蓝色的“播放”，我是选中一个，然后点页面上面的“全部播放”，就可以了，只是播放速度好像不是很好的。

下载还是不行，没有反应，插件里没有Xunlei插件，已经安装FireFox开发版，也装了ThunderAPIHelper_WebExt

**Comment by Cozak** [comment]
在线播放的流畅度取决于115，不是VIP有限速正常

把ThunderAPIHelper_WebExt的安装结果截个图看看，注意安装有两个部分，一个是扩展，一个是NativeApp

**Comment by anymee** [comment]
![4](https://user-images.githubusercontent.com/31944592/33156372-1f18add2-d034-11e7-8f5c-a81e7aa3b0e6.png)

这是没安装成功的意思？

**Comment by Cozak** [comment]
xThunder_Temp.json与install.bat在同一目录下，怎么会没找到

**Comment by anymee** [comment]
就在同一目录下的。上面的乱码怎么回事？

**Comment by Cozak** [comment]
打开install.bat看看就知道，那些中文注释（乱码）删去也无所谓，所谓安装不过是替换Temp的文本生成xThunder.json然后登记注册表而已

**Comment by anymee** [comment]
![7](https://user-images.githubusercontent.com/31944592/33195633-57b54142-d114-11e7-8a85-654694193f9f.png)

帮忙看看，哪里有问题吗？

**Comment by Cozak** [comment]
install.bat的文本内容没问题，你可以新建个bat手打每行命令（除去rem的行）再试试

或者手动模拟install.bat的行为：
直接复制一份xThunder_Temp.json重命名为xThunder.json，然后将里面的"__PATH__"替换为文件所在的当前目录（路径分隔符换为"\\\\"），然后新建一个bat里面只需要用来注册的那行代码即可，然后运行bat

PS：insall.bat的注释已经写得很明白了

**Comment by anymee** [comment]
![8](https://user-images.githubusercontent.com/31944592/33201837-1bd919c0-d135-11e7-8c3c-b78022bc9154.png)

还是不行，点开始下载后出来这个。

路径分隔符换为"\\\\"，是E:\\\\win\\\\xThunder_win.bat这样吗?

**Comment by anymee** [comment]
![11](https://user-images.githubusercontent.com/31944592/33202370-3dd57f9e-d137-11e7-87f2-a48a375a9762.png)

直接运行xThunder.exe出现这个问题

**Comment by Cozak** [comment]
xThunder.exe不是拿来直接运行的。。

弹出![这个](https://user-images.githubusercontent.com/31944592/33201837-1bd919c0-d135-11e7-8c3c-b78022bc9154.png)
说明已经成功调用到xThunder.exe了，只不过你电脑上迅雷的安装可能有问题，从迅雷官网上下载最新版安装试试
